import type { ExpoConfig } from 'expo/config';

/**
 * Native configuration lives here and only here: android/ and ios/ are
 * generated by `expo prebuild` (Continuous Native Generation) and are not
 * committed. Anything that would once have been a hand edit in the native
 * projects is a config plugin or a field below.
 */
// CI passes the release tag (v1.2.3); local builds keep the default.
const version = (process.env.RELAY_VERSION ?? '0.2.0').replace(/^v/, '');
const [major = 0, minor = 0, patch = 0] = version.split(/[.-]/).map((n: string) => Number.parseInt(n, 10) || 0);
/** Monotonic across releases as long as minor and patch stay below 100. */
const versionCode = major * 10_000 + minor * 100 + patch;

const config: ExpoConfig = {
  name: 'Skipper',
  slug: 'relay-controller',
  version,
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'relay',
  userInterfaceStyle: 'dark',
  backgroundColor: '#14181E',
  ios: {
    bundleIdentifier: 'dev.sandoramix.skipper',
    buildNumber: String(versionCode),
    icon: './assets/expo.icon',
    infoPlist: {
      NSLocalNetworkUsageDescription:
        'Skipper cerca il ricevitore sulla tua rete Wi-Fi per comandarlo senza passare da internet.',
      NSBonjourServices: ['_relayctl._tcp'],
      NSBluetoothAlwaysUsageDescription:
        'Skipper usa il Bluetooth per comandare il ricevitore quando non c\'è nessuna rete.',
    },
  },
  android: {
    package: 'dev.sandoramix.skipper',
    versionCode,
    adaptiveIcon: {
      backgroundColor: '#14181E',
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
    permissions: [
      'android.permission.INTERNET',
      'android.permission.ACCESS_NETWORK_STATE',
      'android.permission.ACCESS_WIFI_STATE',
      'android.permission.CHANGE_WIFI_MULTICAST_STATE',
      'android.permission.VIBRATE',
    ],
  },
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: '#14181E',
        image: './assets/images/splash-icon.png',
        imageWidth: 76,
      },
    ],
    [
      'expo-build-properties',
      {
        android: {
          // LAN and a self-hosted relay are plain ws:// on a home network. The
          // HMAC on every frame is what protects them, not TLS.
          usesCleartextTraffic: true,
          minSdkVersion: 26,
        },
        // CI keeps a compiler cache between runs; local builds stay as they were.
        ios: { ccacheEnabled: process.env.RELAY_CCACHE === '1' },
      },
    ],
    [
      'react-native-ble-plx',
      {
        isBackgroundEnabled: false,
        modes: ['central'],
        bluetoothAlwaysPermission:
          'Skipper usa il Bluetooth per comandare il ricevitore quando non c\'è nessuna rete.',
      },
    ],
    [
      '@config-plugins/react-native-webrtc',
      { cameraPermission: false, microphonePermission: false },
    ],
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
};

export default config;
